version: '3.7'

services: 
  database_keep:
    image: postgres
    container_name: database_keep
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=keep_api
    volumes: 
      - pgdata_keep:/data/postgres
    network_mode: host

  keep_api:
    build: ./api
    container_name: keep_api
    ports:
      - 3333:3333
    volumes:
      - ./api:/usr/app
    network_mode: host

volumes:
  pgdata_keep:
    driver: local